import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("countries").del();

  // Inserts seed entries
  await knex("countries").insert([
    { id: 1, name: "Afghanistan", iso_code_2: "AF", iso_code_3: "AFG" },
    { id: 2, name: "Albania", iso_code_2: "AL", iso_code_3: "ALB" },
    { id: 3, name: "Algeria", iso_code_2: "DZ", iso_code_3: "DZA" },
    { id: 4, name: "American Samoa", iso_code_2: "AS", iso_code_3: "ASM" },
    { id: 5, name: "Andorra", iso_code_2: "AD", iso_code_3: "AND" },
    { id: 6, name: "Angola", iso_code_2: "AO", iso_code_3: "AGO" },
    { id: 7, name: "Anguilla", iso_code_2: "AI", iso_code_3: "AIA" },
    { id: 8, name: "Antarctica", iso_code_2: "AQ", iso_code_3: "ATA" },
    { id: 9, name: "Antigua and Barbuda", iso_code_2: "AG", iso_code_3: "ATG" },
    { id: 10, name: "Argentina", iso_code_2: "AR", iso_code_3: "ARG" },
    { id: 11, name: "Armenia", iso_code_2: "AM", iso_code_3: "ARM" },
    { id: 12, name: "Aruba", iso_code_2: "AW", iso_code_3: "ABW" },
    { id: 13, name: "Australia", iso_code_2: "AU", iso_code_3: "AUS" },
    { id: 14, name: "Austria", iso_code_2: "AT", iso_code_3: "AUT" },
    { id: 15, name: "Azerbaijan", iso_code_2: "AZ", iso_code_3: "AZE" },
    { id: 16, name: "Bahamas", iso_code_2: "BS", iso_code_3: "BHS" },
    { id: 17, name: "Bahrain", iso_code_2: "BH", iso_code_3: "BHR" },
    { id: 18, name: "Bangladesh", iso_code_2: "BD", iso_code_3: "BGD" },
    { id: 19, name: "Barbados", iso_code_2: "BB", iso_code_3: "BRB" },
    { id: 20, name: "Belarus", iso_code_2: "BY", iso_code_3: "BLR" },
    { id: 21, name: "Belgium", iso_code_2: "BE", iso_code_3: "BEL" },
    { id: 22, name: "Belize", iso_code_2: "BZ", iso_code_3: "BLZ" },
    { id: 23, name: "Benin", iso_code_2: "BJ", iso_code_3: "BEN" },
    { id: 24, name: "Bermuda", iso_code_2: "BM", iso_code_3: "BMU" },
    { id: 25, name: "Bhutan", iso_code_2: "BT", iso_code_3: "BTN" },
    { id: 26, name: "Bhutan", iso_code_2: "BT", iso_code_3: "BTN" },
    { id: 27, name: "Bolivia", iso_code_2: "BO", iso_code_3: "BOL" },
    { id: 28, name: "Bosnia and Herzegowina", iso_code_2: "BA", iso_code_3: "BIH" },
    { id: 29, name: "Botswana", iso_code_2: "BW", iso_code_3: "BWA" },
    { id: 30, name: "Bouvet Island", iso_code_2: "BV", iso_code_3: "BVT" },
    { id: 31, name: "Brazil", iso_code_2: "BR", iso_code_3: "BRA" },
    { id: 32, name: "British Indian Ocean Territory", iso_code_2: "IO", iso_code_3: "IOT" },
    { id: 33, name: "Brunei Darussalam", iso_code_2: "BN", iso_code_3: "BRN" },
    { id: 34, name: "Bulgaria", iso_code_2: "BG", iso_code_3: "BGR" },
    { id: 35, name: "Burkina Faso", iso_code_2: "BF", iso_code_3: "BFA" },
    { id: 36, name: "Burundi", iso_code_2: "BI", iso_code_3: "BDI" },
    { id: 37, name: "Cambodia", iso_code_2: "KH", iso_code_3: "KHM" },
    { id: 38, name: "Cameroon", iso_code_2: "CM", iso_code_3: "CMR" },
    { id: 39, name: "Canada", iso_code_2: "CA", iso_code_3: "CAN" },
    { id: 40, name: "Cape Verde", iso_code_2: "CV", iso_code_3: "CPV" },
    { id: 41, name: "Cayman Islands", iso_code_2: "KY", iso_code_3: "CYM" },
    { id: 42, name: "Central African Republic", iso_code_2: "CF", iso_code_3: "CAF" },
    { id: 43, name: "Chad", iso_code_2: "TD", iso_code_3: "TCD" },
    { id: 44, name: "Chile", iso_code_2: "CL", iso_code_3: "CHL" },
    { id: 45, name: "China", iso_code_2: "CN", iso_code_3: "CHN" },
    { id: 46, name: "Christmas Island", iso_code_2: "CX", iso_code_3: "CXR" },
    { id: 47, name: "Cocos (Keeling) Islands", iso_code_2: "CC", iso_code_3: "CCK" },
    { id: 48, name: "Colombia", iso_code_2: "CO", iso_code_3: "COL" },
    { id: 49, name: "Comoros", iso_code_2: "KM", iso_code_3: "COM" },
    { id: 50, name: "Congo", iso_code_2: "CG", iso_code_3: "COG" },
    { id: 51, name: "Cook Islands", iso_code_2: "CK", iso_code_3: "COK" },
    { id: 52, name: "Costa Rica", iso_code_2: "CR", iso_code_3: "CRI" },
    { id: 53, name: "Cote D'Ivoire", iso_code_2: "CI", iso_code_3: "CIV" },
    { id: 54, name: "Croatia", iso_code_2: "HR", iso_code_3: "HRV" },
    { id: 55, name: "Cuba", iso_code_2: "CU", iso_code_3: "CUB" },
    { id: 56, name: "Cyprus", iso_code_2: "CY", iso_code_3: "CYP" },
    { id: 57, name: "Czech Republic", iso_code_2: "CZ", iso_code_3: "CZE" },
    { id: 58, name: "Democratic Republic of Congo", iso_code_2: "CD", iso_code_3: "COD" },
    { id: 59, name: "Denmark", iso_code_2: "DK", iso_code_3: "DNK" },
    { id: 60, name: "Djibouti", iso_code_2: "DJ", iso_code_3: "DJI" },
    { id: 61, name: "Dominica", iso_code_2: "DM", iso_code_3: "DMA" },
    { id: 62, name: "Dominican Republic", iso_code_2: "DO", iso_code_3: "DOM" },
    { id: 63, name: "East Timor", iso_code_2: "TP", iso_code_3: "TMP" },
    { id: 64, name: "Ecuador", iso_code_2: "EC", iso_code_3: "ECU" },
    { id: 65, name: "Egypt", iso_code_2: "EG", iso_code_3: "EGY" },
    { id: 66, name: "El Salvador", iso_code_2: "SV", iso_code_3: "SLV" },
    { id: 67, name: "Equatorial Guinea", iso_code_2: "GQ", iso_code_3: "GNQ" },
    { id: 68, name: "Eritrea", iso_code_2: "ER", iso_code_3: "ERI" },
    { id: 69, name: "Estonia", iso_code_2: "EE", iso_code_3: "EST" },
    { id: 70, name: "Ethiopia", iso_code_2: "ET", iso_code_3: "ETH" },
    { id: 71, name: "Falkland Islands (Malvinas)", iso_code_2: "FK", iso_code_3: "FLK" },
    { id: 72, name: "Faroe Islands", iso_code_2: "FO", iso_code_3: "FRO" },
    { id: 73, name: "Fiji", iso_code_2: "FJ", iso_code_3: "FJI" },
    { id: 74, name: "Finland", iso_code_2: "FI", iso_code_3: "FIN" },
    { id: 75, name: "France", iso_code_2: "FR", iso_code_3: "FRA" },
    { id: 76, name: "France, Metropolitan", iso_code_2: "FX", iso_code_3: "FXX" },
    { id: 77, name: "French Guiana", iso_code_2: "GF", iso_code_3: "GUF" },
    { id: 78, name: "French Polynesia", iso_code_2: "PF", iso_code_3: "PYF" },
    { id: 79, name: "Gabon", iso_code_2: "GA", iso_code_3: "GAB" },
    { id: 80, name: "Gambia", iso_code_2: "GM", iso_code_3: "GMB" },
    { id: 81, name: "Georgia", iso_code_2: "GE", iso_code_3: "GEO" },
    { id: 82, name: "Germany", iso_code_2: "DE", iso_code_3: "DEU" },
    { id: 83, name: "Ghana", iso_code_2: "GH", iso_code_3: "GHA" },
    { id: 84, name: "Gibraltar", iso_code_2: "GI", iso_code_3: "GIB" },
    { id: 85, name: "Greece", iso_code_2: "GR", iso_code_3: "GRC" },
    { id: 86, name: "Greenland", iso_code_2: "GL", iso_code_3: "GRL" },
    { id: 87, name: "Grenada", iso_code_2: "GD", iso_code_3: "GRD" },
    { id: 88, name: "Guadeloupe", iso_code_2: "GP", iso_code_3: "GLP" },
    { id: 89, name: "Guam", iso_code_2: "GU", iso_code_3: "GUM" },
    { id: 90, name: "Guatemala", iso_code_2: "GT", iso_code_3: "GTM" },
    { id: 91, name: "Guinea", iso_code_2: "GN", iso_code_3: "GIN" },
    { id: 92, name: "Guinea-Bissau", iso_code_2: "GW", iso_code_3: "GNB" },
    { id: 93, name: "Guyana", iso_code_2: "GY", iso_code_3: "GUY" },
    { id: 94, name: "Haiti", iso_code_2: "HT", iso_code_3: "HTI" },
    { id: 95, name: "Heard and Mc Donald Islands", iso_code_2: "HM", iso_code_3: "HMD" },
    { id: 96, name: "Honduras", iso_code_2: "HN", iso_code_3: "HND" },
    { id: 97, name: "Hong Kong", iso_code_2: "HK", iso_code_3: "HKG" },
    { id: 98, name: "Hungary", iso_code_2: "HU", iso_code_3: "HUN" },
    { id: 99, name: "Iceland", iso_code_2: "IS", iso_code_3: "ISL" },
    { id: 100, name: "India", iso_code_2: "IN", iso_code_3: "IND" },
    { id: 101, name: "Indonesia", iso_code_2: "ID", iso_code_3: "IDN" },
    { id: 102, name: "Iran", iso_code_2: "IR", iso_code_3: "IRN" },
    { id: 103, name: "Iraq", iso_code_2: "IQ", iso_code_3: "IRQ" },
    { id: 104, name: "Ireland", iso_code_2: "IE", iso_code_3: "IRL" },
    { id: 105, name: "Israel", iso_code_2: "IL", iso_code_3: "ISR" },
    { id: 106, name: "Italy", iso_code_2: "IT", iso_code_3: "ITA" },
    { id: 107, name: "Jamaica", iso_code_2: "JM", iso_code_3: "JAM" },
    { id: 108, name: "Japan", iso_code_2: "JP", iso_code_3: "JPN" },
    { id: 109, name: "Jordan", iso_code_2: "JO", iso_code_3: "JOR" },
    { id: 110, name: "Kazakhstan", iso_code_2: "KZ", iso_code_3: "KAZ" },
    { id: 111, name: "Kenya", iso_code_2: "KE", iso_code_3: "KEN" },
    { id: 112, name: "Kiribati", iso_code_2: "KI", iso_code_3: "KIR" },
    { id: 113, name: "Korea", iso_code_2: "KR", iso_code_3: "KOR" },
    { id: 114, name: "Kuwait", iso_code_2: "KW", iso_code_3: "KWT" },
    { id: 115, name: "Kyrgyzstan", iso_code_2: "KG", iso_code_3: "KGZ" },
    { id: 116, name: "Lao People's Democratic Republic", iso_code_2: "LA", iso_code_3: "LAO" },
    { id: 117, name: "Latvia", iso_code_2: "LV", iso_code_3: "LVA" },
    { id: 118, name: "Lebanon", iso_code_2: "LB", iso_code_3: "LBN" },
    { id: 119, name: "Lesotho", iso_code_2: "LS", iso_code_3: "LSO" },
    { id: 120, name: "Liberia", iso_code_2: "LR", iso_code_3: "LBR" },
    { id: 121, name: "Libyan Arab Jamahiriya", iso_code_2: "LY", iso_code_3: "LBY" },
    { id: 122, name: "Liechtenstein", iso_code_2: "LI", iso_code_3: "LIE" },
    { id: 123, name: "Lithuania", iso_code_2: "LT", iso_code_3: "LTU" },
    { id: 124, name: "Luxembourg", iso_code_2: "LU", iso_code_3: "LUX" },
    { id: 125, name: "Macau", iso_code_2: "MO", iso_code_3: "MAC" },
    { id: 126, name: "Macedonia", iso_code_2: "MK", iso_code_3: "MKD" },
    { id: 127, name: "Madagascar", iso_code_2: "MG", iso_code_3: "MDG" },
    { id: 128, name: "Malawi", iso_code_2: "MW", iso_code_3: "MWI" },
    { id: 129, name: "Malaysia", iso_code_2: "MY", iso_code_3: "MYS" },
    { id: 130, name: "Maldives", iso_code_2: "MV", iso_code_3: "MDV" },
    { id: 131, name: "Mali", iso_code_2: "ML", iso_code_3: "MLI" },
    { id: 132, name: "Malta", iso_code_2: "MT", iso_code_3: "MLT" },
    { id: 133, name: "Marshall Islands", iso_code_2: "MH", iso_code_3: "MHL" },
    { id: 134, name: "Martinique", iso_code_2: "MQ", iso_code_3: "MTQ" },
    { id: 135, name: "Mauritania", iso_code_2: "MR", iso_code_3: "MRT" },
    { id: 136, name: "Mauritius", iso_code_2: "MU", iso_code_3: "MUS" },
    { id: 137, name: "Mayotte", iso_code_2: "YT", iso_code_3: "MYT" },
    { id: 138, name: "Mexico", iso_code_2: "MX", iso_code_3: "MEX" },
    { id: 139, name: "Micronesia", iso_code_2: "FM", iso_code_3: "FSM" },
    { id: 140, name: "Micronesia", iso_code_2: "FM", iso_code_3: "FSM" },
    { id: 141, name: "Moldova", iso_code_2: "MD", iso_code_3: "MDA" },
    { id: 142, name: "Monaco", iso_code_2: "MC", iso_code_3: "MCO" },
    { id: 143, name: "Mongolia", iso_code_2: "MN", iso_code_3: "MNG" },
    { id: 144, name: "Montserrat", iso_code_2: "MS", iso_code_3: "MSR" },
    { id: 145, name: "Morocco", iso_code_2: "MA", iso_code_3: "MAR" },
    { id: 146, name: "Mozambique", iso_code_2: "MZ", iso_code_3: "MOZ" },
    { id: 147, name: "Myanmar", iso_code_2: "MM", iso_code_3: "MMR" },
    { id: 148, name: "Namibia", iso_code_2: "NA", iso_code_3: "NAM" },
    { id: 149, name: "Nauru", iso_code_2: "NR", iso_code_3: "NRU" },
    { id: 150, name: "Nepal", iso_code_2: "NP", iso_code_3: "NPL" },
    { id: 151, name: "Netherlands", iso_code_2: "NL", iso_code_3: "NLD" },
    { id: 152, name: "Netherlands Antilles", iso_code_2: "AN", iso_code_3: "ANT" },
    { id: 153, name: "New Caledonia", iso_code_2: "NC", iso_code_3: "NCL" },
    { id: 154, name: "New Zealand", iso_code_2: "NZ", iso_code_3: "NZL" },
    { id: 155, name: "Nicaragua", iso_code_2: "NI", iso_code_3: "NIC" },
    { id: 156, name: "Niger", iso_code_2: "NE", iso_code_3: "NER" },
    { id: 157, name: "Nigeria", iso_code_2: "NG", iso_code_3: "NGA" },
    { id: 158, name: "Niue", iso_code_2: "NU", iso_code_3: "NIU" },
    { id: 159, name: "Norfolk Island", iso_code_2: "NF", iso_code_3: "NFK" },
    { id: 160, name: "North Korea", iso_code_2: "KP", iso_code_3: "PRK" },
    { id: 161, name: "Northern Mariana Islands", iso_code_2: "MP", iso_code_3: "MNP" },
    { id: 162, name: "Norway", iso_code_2: "NO", iso_code_3: "NOR" },
    { id: 163, name: "Oman", iso_code_2: "OM", iso_code_3: "OMN" },
    { id: 164, name: "Pakistan", iso_code_2: "PK", iso_code_3: "PAK" },
    { id: 165, name: "Palau", iso_code_2: "PW", iso_code_3: "PLW" },
    { id: 166, name: "Panama", iso_code_2: "PA", iso_code_3: "PAN" },
    { id: 167, name: "Papua New Guinea", iso_code_2: "PG", iso_code_3: "PNG" },
    { id: 168, name: "Paraguay", iso_code_2: "PY", iso_code_3: "PRY" },
    { id: 169, name: "Peru", iso_code_2: "PE", iso_code_3: "PER" },
    { id: 170, name: "Philippines", iso_code_2: "PH", iso_code_3: "PHL" },
    { id: 171, name: "Pitcairn", iso_code_2: "PN", iso_code_3: "PCN" },
    { id: 172, name: "Poland", iso_code_2: "PL", iso_code_3: "POL" },
    { id: 173, name: "Portugal", iso_code_2: "PT", iso_code_3: "PRT" },
    { id: 174, name: "Puerto Rico", iso_code_2: "PR", iso_code_3: "PRI" },
    { id: 175, name: "Qatar", iso_code_2: "QA", iso_code_3: "QAT" },
    { id: 176, name: "Reunion", iso_code_2: "RE", iso_code_3: "REU" },
    { id: 177, name: "Romania", iso_code_2: "RO", iso_code_3: "ROM" },
    { id: 178, name: "Russian Federation", iso_code_2: "RU", iso_code_3: "RUS" },
    { id: 179, name: "Rwanda", iso_code_2: "RW", iso_code_3: "RWA" },
    { id: 180, name: "Saint Kitts and Nevis", iso_code_2: "KN", iso_code_3: "KNA" },
    { id: 181, name: "Saint Lucia", iso_code_2: "LC", iso_code_3: "LCA" },
    { id: 182, name: "Saint Vincent and the Grenadines", iso_code_2: "VC", iso_code_3: "VCT" },
    { id: 183, name: "Samoa", iso_code_2: "WS", iso_code_3: "WSM" },
    { id: 184, name: "San Marino", iso_code_2: "SM", iso_code_3: "SMR" },
    { id: 185, name: "Sao Tome and Principe", iso_code_2: "ST", iso_code_3: "STP" },
    { id: 186, name: "Saudi Arabia", iso_code_2: "SA", iso_code_3: "SAU" },
    { id: 187, name: "Senegal", iso_code_2: "SN", iso_code_3: "SEN" },
    { id: 188, name: "Seychelles", iso_code_2: "SC", iso_code_3: "SYC" },
    { id: 189, name: "Sierra Leone", iso_code_2: "SL", iso_code_3: "SLE" },
    { id: 190, name: "Singapore", iso_code_2: "SG", iso_code_3: "SGP" },
    { id: 191, name: "Slovak Republic", iso_code_2: "SK", iso_code_3: "SVK" },
    { id: 192, name: "Slovenia", iso_code_2: "SI", iso_code_3: "SVN" },
    { id: 193, name: "Solomon Islands", iso_code_2: "SB", iso_code_3: "SLB" },
    { id: 194, name: "Somalia", iso_code_2: "SO", iso_code_3: "SOM" },
    { id: 195, name: "South Africa", iso_code_2: "ZA", iso_code_3: "ZAF" },
    { id: 196, name: "South Georgia & South Sandwich Islands", iso_code_2: "GS", iso_code_3: "SGS" },
    { id: 197, name: "Spain", iso_code_2: "ES", iso_code_3: "ESP" },
    { id: 198, name: "Sri Lanka", iso_code_2: "LK", iso_code_3: "LKA" },
    { id: 199, name: "St. Helena", iso_code_2: "SH", iso_code_3: "SHN" },
    { id: 200, name: "St. Pierre and Miquelon", iso_code_2: "PM", iso_code_3: "SPM" },
    { id: 201, name: "Sudan", iso_code_2: "SD", iso_code_3: "SDN" },
    { id: 202, name: "Suriname", iso_code_2: "SR", iso_code_3: "SUR" },
    { id: 203, name: "Svalbard and Jan Mayen Islands", iso_code_2: "SJ", iso_code_3: "SJM" },
    { id: 204, name: "Swaziland", iso_code_2: "SZ", iso_code_3: "SWZ" },
    { id: 205, name: "Sweden", iso_code_2: "SE", iso_code_3: "SWE" },
    { id: 206, name: "Switzerland", iso_code_2: "CH", iso_code_3: "CHE" },
    { id: 207, name: "Syrian Arab Republic", iso_code_2: "SY", iso_code_3: "SYR" },
    { id: 208, name: "Taiwan", iso_code_2: "TW", iso_code_3: "TWN" },
    { id: 209, name: "Tajikistan", iso_code_2: "TJ", iso_code_3: "TJK" },
    { id: 210, name: "Tanzania", iso_code_2: "TZ", iso_code_3: "TZA" },
    { id: 211, name: "Thailand", iso_code_2: "TH", iso_code_3: "THA" },
    { id: 212, name: "Togo", iso_code_2: "TG", iso_code_3: "TGO" },
    { id: 213, name: "Tokelau", iso_code_2: "TK", iso_code_3: "TKL" },
    { id: 214, name: "Tonga", iso_code_2: "TO", iso_code_3: "TON" },
    { id: 215, name: "Trinidad and Tobago", iso_code_2: "TT", iso_code_3: "TTO" },
    { id: 216, name: "Tunisia", iso_code_2: "TN", iso_code_3: "TUN" },
    { id: 217, name: "Turkey", iso_code_2: "TR", iso_code_3: "TUR" },
    { id: 218, name: "Turkmenistan", iso_code_2: "TM", iso_code_3: "TKM" },
    { id: 219, name: "Turks and Caicos Islands", iso_code_2: "TC", iso_code_3: "TCA" },
    { id: 220, name: "Tuvalu", iso_code_2: "TV", iso_code_3: "TUV" },
    { id: 221, name: "Uganda", iso_code_2: "UG", iso_code_3: "UGA" },
    { id: 222, name: "Ukraine", iso_code_2: "UA", iso_code_3: "UKR" },
    { id: 223, name: "United Arab Emirates", iso_code_2: "AE", iso_code_3: "ARE" },
    { id: 224, name: "United Kingdom", iso_code_2: "GB", iso_code_3: "GBR" },
    { id: 225, name: "United States", iso_code_2: "US", iso_code_3: "USA" },
    { id: 226, name: "United States Minor Outlying Islands", iso_code_2: "UM", iso_code_3: "UMI" },
    { id: 227, name: "Uruguay", iso_code_2: "UY", iso_code_3: "URY" },
    { id: 228, name: "Uzbekistan", iso_code_2: "UZ", iso_code_3: "UZB" },
    { id: 229, name: "Vanuatu", iso_code_2: "VU", iso_code_3: "VUT" },
    { id: 230, name: "Vatican City State (Holy See)", iso_code_2: "VA", iso_code_3: "VAT" },
    { id: 231, name: "Venezuela", iso_code_2: "VE", iso_code_3: "VEN" },
    { id: 232, name: "Viet Nam", iso_code_2: "VN", iso_code_3: "VNM" },
    { id: 233, name: "Virgin Islands (British)", iso_code_2: "VG", iso_code_3: "VGB" },
    { id: 234, name: "Virgin Islands (U.S.)", iso_code_2: "VI", iso_code_3: "VIR" },
    { id: 235, name: "Wallis and Futuna Islands", iso_code_2: "WF", iso_code_3: "WLF" },
    { id: 236, name: "Western Sahara", iso_code_2: "EH", iso_code_3: "ESH" },
    { id: 237, name: "Yemen", iso_code_2: "YE", iso_code_3: "YEM" },
    { id: 238, name: "Yugoslavia", iso_code_2: "YU", iso_code_3: "YUG" },
    { id: 239, name: "Zambia", iso_code_2: "ZM", iso_code_3: "ZMB" },
    { id: 240, name: "Zimbabwe", iso_code_2: "ZW", iso_code_3: "ZWE" },
  ]);
};
