import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("currencies").del();

  // Inserts seed entries
  await knex("currencies").insert([
    { iso: "AED", title: "United Arab Emirates dirham" },
    { iso: "AFN", title: "Afghani" },
    { iso: "ALL", title: "Lek" },
    { iso: "AMD", title: "Armenian Dram" },
    { iso: "ANG", title: "Netherlands Antillian Guilder" },
    { iso: "AOA", title: "Kwanza" },
    { iso: "ARS", title: "Argentine Peso" },
    { iso: "AUD", title: "Australian Dollar" },
    { iso: "AWG", title: "Aruban Guilder" },
    { iso: "AZN", title: "Azerbaijanian Manat" },
    { iso: "BAM", title: "Convertible Marks" },
    { iso: "BBD", title: "Barbados Dollar" },
    { iso: "BDT", title: "Bangladeshi Taka" },
    { iso: "BGN", title: "Bulgarian Lev" },
    { iso: "BHD", title: "Bahraini Dinar" },
    { iso: "BIF", title: "Burundian Franc" },
    { iso: "BMD", title: "Bermudian Dollar" },
    { iso: "BND", title: "Brunei Dollar" },
    { iso: "BOB", title: "Boliviano" },
    { iso: "BOV", title: "Bolivian Mvdol" },
    { iso: "BRL", title: "Brazilian Real" },
    { iso: "BSD", title: "Bahamian Dollar" },
    { iso: "BTN", title: "Ngultrum" },
    { iso: "BWP", title: "Pula" },
    { iso: "BYR", title: "Belarussian Ruble" },
    { iso: "BZD", title: "Belize Dollar" },
    { iso: "CAD", title: "Canadian Dollar" },
    { iso: "CDF", title: "Franc Congolais" },
    { iso: "CHE", title: "WIR Euro" },
    { iso: "CHF", title: "Swiss Franc" },
    { iso: "CHW", title: "WIR Franc" },
    { iso: "CLF", title: "Unidades de formento" },
    { iso: "CLP", title: "Chilean Peso" },
    { iso: "CNY", title: "Yuan Renminbi" },
    { iso: "COP", title: "Colombian Peso" },
    { iso: "COU", title: "Unidad de Valor Real" },
    { iso: "CRC", title: "Costa Rican Colon" },
    { iso: "CUP", title: "Cuban Peso" },
    { iso: "CVE", title: "Cape Verde Escudo" },
    { iso: "CYP", title: "Cyprus Pound" },
    { iso: "CZK", title: "Czech Koruna" },
    { iso: "DJF", title: "Djibouti Franc" },
    { iso: "DKK", title: "Danish Krone" },
    { iso: "DOP", title: "Dominican Peso" },
    { iso: "DZD", title: "Algerian Dinar" },
    { iso: "EEK", title: "Kroon" },
    { iso: "EGP", title: "Egyptian Pound" },
    { iso: "ERN", title: "Nakfa" },
    { iso: "ETB", title: "Ethiopian Birr" },
    { iso: "EUR", title: "Euro" },
    { iso: "FJD", title: "Fiji Dollar" },
    { iso: "FKP", title: "Falkland Islands Pound" },
    { iso: "GBP", title: "Pound Sterling" },
    { iso: "GEL", title: "Lari" },
    { iso: "GHS", title: "Cedi" },
    { iso: "GIP", title: "Gibraltar pound" },
    { iso: "GMD", title: "Dalasi" },
    { iso: "GNF", title: "Guinea Franc" },
    { iso: "GTQ", title: "Quetzal" },
    { iso: "GYD", title: "Guyana Dollar" },
    { iso: "HKD", title: "Hong Kong Dollar" },
    { iso: "HNL", title: "Lempira" },
    { iso: "HRK", title: "Croatian Kuna" },
    { iso: "HTG", title: "Haiti Gourde" },
    { iso: "HUF", title: "Forint" },
    { iso: "IDR", title: "Rupiah" },
    { iso: "ILS", title: "New Israeli Shekel" },
    { iso: "INR", title: "Indian Rupee" },
    { iso: "IQD", title: "Iraqi Dinar" },
    { iso: "IRR", title: "Iranian Rial" },
    { iso: "ISK", title: "Iceland Krona" },
    { iso: "JMD", title: "Jamaican Dollar" },
    { iso: "JOD", title: "Jordanian Dinar" },
    { iso: "JPY", title: "Japanese yen" },
    { iso: "KES", title: "Kenyan Shilling" },
    { iso: "KGS", title: "Som" },
    { iso: "KHR", title: "Riel" },
    { iso: "KMF", title: "Comoro Franc" },
    { iso: "KPW", title: "North Korean Won" },
    { iso: "KRW", title: "South Korean Won" },
    { iso: "KWD", title: "Kuwaiti Dinar" },
    { iso: "KYD", title: "Cayman Islands Dollar" },
    { iso: "KZT", title: "Tenge" },
    { iso: "LAK", title: "Kip" },
    { iso: "LBP", title: "Lebanese Pound" },
    { iso: "LKR", title: "Sri Lanka Rupee" },
    { iso: "LRD", title: "Liberian Dollar" },
    { iso: "LSL", title: "Loti" },
    { iso: "LTL", title: "Lithuanian Litas" },
    { iso: "LVL", title: "Latvian Lats" },
    { iso: "LYD", title: "Libyan Dinar" },
    { iso: "MAD", title: "Moroccan Dirham" },
    { iso: "MDL", title: "Moldovan Leu" },
    { iso: "MGA", title: "Malagasy Ariary" },
    { iso: "MKD", title: "Denar" },
    { iso: "MMK", title: "Kyat" },
    { iso: "MNT", title: "Tugrik" },
    { iso: "MOP", title: "Pataca" },
    { iso: "MRO", title: "Ouguiya" },
    { iso: "MTL", title: "Maltese Lira" },
    { iso: "MUR", title: "Mauritius Rupee" },
    { iso: "MVR", title: "Rufiyaa" },
    { iso: "MWK", title: "Kwacha" },
    { iso: "MXN", title: "Mexican Peso" },
    { iso: "MXV", title: "Mexican Unidad de Inversion (UDI)" },
    { iso: "MYR", title: "Malaysian Ringgit" },
    { iso: "MZN", title: "Metical" },
    { iso: "NAD", title: "Namibian Dollar" },
    { iso: "NGN", title: "Naira" },
    { iso: "NIO", title: "Cordoba Oro" },
    { iso: "NOK", title: "Norwegian Krone" },
    { iso: "NPR", title: "Nepalese Rupee" },
    { iso: "NZD", title: "New Zealand Dollar" },
    { iso: "OMR", title: "Rial Omani" },
    { iso: "PAB", title: "Balboa" },
    { iso: "PEN", title: "Nuevo Sol" },
    { iso: "PGK", title: "Kina" },
    { iso: "PHP", title: "Philippine Peso" },
    { iso: "PKR", title: "Pakistan Rupee" },
    { iso: "PLN", title: "Zloty" },
    { iso: "PYG", title: "Guarani" },
    { iso: "QAR", title: "Qatari Rial" },
    { iso: "RON", title: "Romanian New Leu" },
    { iso: "RSD", title: "Serbian Dinar" },
    { iso: "RUB", title: "Russian Ruble" },
    { iso: "RWF", title: "Rwanda Franc" },
    { iso: "SAR", title: "Saudi Riyal" },
    { iso: "SBD", title: "Solomon Islands Dollar" },
    { iso: "SCR", title: "Seychelles Rupee" },
    { iso: "SDG", title: "Sudanese Pound" },
    { iso: "SEK", title: "Swedish Krona" },
    { iso: "SGD", title: "Singapore Dollar" },
    { iso: "SHP", title: "Saint Helena Pound" },
    { iso: "SKK", title: "Slovak Koruna" },
    { iso: "SLL", title: "Leone" },
    { iso: "SOS", title: "Somali Shilling" },
    { iso: "SRD", title: "Surinam Dollar" },
    { iso: "STD", title: "Dobra" },
    { iso: "SYP", title: "Syrian Pound" },
    { iso: "SZL", title: "Lilangeni" },
    { iso: "THB", title: "Baht" },
    { iso: "TJS", title: "Somoni" },
    { iso: "TMM", title: "Manat" },
    { iso: "TND", title: "Tunisian Dinar" },
    { iso: "TOP", title: "Pa'anga" },
    { iso: "TRY", title: "New Turkish Lira" },
    { iso: "TTD", title: "Trinidad and Tobago Dollar" },
    { iso: "TWD", title: "New Taiwan Dollar" },
    { iso: "TZS", title: "Tanzanian Shilling" },
    { iso: "UAH", title: "Hryvnia" },
    { iso: "UGX", title: "Uganda Shilling" },
    { iso: "USD", title: "United States Dollar" },
    { iso: "XAF", title: "CFA Franc BEAC" },
    { iso: "XAG", title: "Silver (one troy ounce)" },
    { iso: "XAU", title: "Gold (one troy ounce)" },
    { iso: "XCD", title: "East Carribean Dollar" },
    { iso: "XPT", title: "Palladium (one troy ounce)" },
    { iso: "XXX", title: "No Currency" },
  ]);
};
